### ISSUE TITLE
lil question..

### ISSUE THREAD

**Issue by blackcrack** [seanox/virtual-environment#2]
Hi, 

because the Developer is an German, would i for better connectivity speak German.. thank you for your understand :))

Hi Seanox,

kleine Frage, bevor ich da drann geh.. und wir haben leider kein Disskussionsforum hier..
Warum nicht ab Win7, weil Win ist noch das System was so weit am WinXP ähnlichsten ist, bei Win10 ist alles
so derbe geführt , wenn Du weist was ich meine.. und auch die Programmblacklisting und AV, das auch über ein VirtualFS verfüght und ohne zu fragen übers Netzwerk scannt und noch andere Sachen.. deshalb möcht ich doch ganz gern bei Win7 die nächsten jahre bleiben, auch hab ich mir ein 17Gig pack batch update-script gebastelt blackysgate.de/files für Win7, so kann ich ein sauberes Win7 installieren..
Also, warum nich von Win7 ab gesupport, wenn da auch Net 4.8 inne ist :)  danke Dir für die Antwort :)

liebe Grüße
best regards
Blacky

**Comment by seanox** [comment]
Hallo Blacky,

Windows 7 wird nicht erwähnt, weil ich nach dem EOL keine Testumgebung für Windows 7 habe.
Technisch sind mir keine Anforderungen bekannt, die gegen Windows 7 sprechen -- es ist nur nicht damit getestet.

Windows 7 is not mentioned because I don't have a test environment for Windows 7 after the EOL.
Technically, I'm not aware of any requirements that speak against Windows 7 -- it's just not tested with it.

Viele Grüsse / best regards,
Simon

**Comment by seanox** [comment]
Wenn es spezielle Anforderungen oder Probleme mit Windows 7 gibt, können wir das in einen eigenen Ticket bearbeiten.

If there are special requirements or problems with Windows 7, we can handle that in a separate ticket.

**Comment by blackcrack** [comment]
Hi @seanox ,
Ich hab ein Upgradpack mit 17 Gig gebaut, wo beim update jedes einzelne oder zumindest die zu 80/90% Updates bis 
zum 2023.06 installiert wird, incl zwei patches.. gut, das zweite patch muss man nach dem Upgrade noch laufen lassen,
dass es bis zum Emdemded ende, also ich glaub 2025 immer geuptated wird.. wenn Du interresse daran hast, , lad dir das actuelle bat file runter, lad die updates und Du hast ein updatepack, das auf dem aktuellem stand ist..,
das ESU bekommst Du bei Deskmodder und das WU"E" auch, auf der gleichen Seite, dann kannst Du mit Win7 bis 2025 arbeiten... musst nur ca 100 files vom Windows Update Catalog runterladen.. die files sind im batch gelistet :)
Somit ist dann auch gewährleistet, daß Dein Proggy von Win7 bis 13 kompatiebel ist beim im Virtualvox testen oder so :)

ein paar Files bekommt man auch nicht mehr und den IE bracht man auch nich mehr.. 
die files für den IE hab ich von fremd Seiten runter geladen wo ich mir sicher war..

also, wenn Du Bock hast, noch ein Win7 und ein updatepack zusammen zu downloaden, 
zieh dir das [setup-update-batch ](https://blackysgate.de/files/folder-root/batch-files) ,
dann hast Du ein ordendliches Upgradepack für die nächsten Jahre :)

das Ding kannste auch für unattended installs verwenden nach dem upgrade, die batch installiert dir alles 
was Du willst hintereinander :) Und so kannst Du noch leute bedienen, die gern bei Win7 bleiben möchten..
und ich denk, daß sind hauptsächlich die richtigen Geeks wie ich, die wissen, was sie am Win7/XP haben ;)
Denn Leute wie uns, haben erst die Software kostenlos in den Firmen verteilt damals ;)

Einen extra tread brauchen wir nich machen dafür, das kommt auf, wenn Du hinschreibst Windows 7/10/11,
dann werden sich auch die Leutz melden, die noch bei Win7 bleiben..

viele liebe Grüße
Blacky
